[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@host.docker.internal:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.mainnet]
shard = "primary"
provider = [
    { label = "block-ingestor", url = "$ETH_MAINNET_RPC", features = [] },
    { label = "substreams-mainnet", details = { type = "substreams", url = "$SUBSTREAMS_ENDPOINT", token = "$SUBSTREAMS_API_TOKEN" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
